<a href="https://colab.research.google.com/github/Piskorro/machine-learning-bootcamp/blob/main/Copy_of_data_pre_processing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Data pre-processing:
1. [Library installation](#0)
2. [Library Actualization](#1)
3. [Library instalation](#2)
4. [Data generation](#3)
5. [Backup](#4)
6. [Change of data type](#5)
7. [LabelEncoder](#6)
8. [OneHotEncoder](#7)
8. [Pandas get Dummies()](#8)





### <a name='0'></a> Library installation


In [ ]:
!pip install scikit-learn

### <a name='1'> </a> Library Actualization

In [ ]:
!pip install --upgrade scikit-learn

     |████████████████████████████████| 22.3 MB 1.4 MB/s 
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 0.22.2.post1
    Uninstalling scikit-learn-0.22.2.post1:
      Successfully uninstalled scikit-learn-0.22.2.post1


### <a name='2'></a> Library instalation

In [4]:
import numpy as np
import pandas as pd
import sklearn

sklearn.__version__

'0.22.2.post1'

### <a name = '3'></a> Data generation

In [13]:
data = {
    'size':['XL','L','M','L','M'],
    'color':['red','green','blue','green','red'],
    'gender':['female','male','male','female','female'],
    'price':[199.0, 89.0, 99.0, 129.0, 79.0],
    'weight':[500, 450, 300, 380, 410],
    'bought':['yes','no','yes','no','yes']
}
My_data = pd.DataFrame(data=data)
My_data


size  color  gender  price  weight bought
0   XL    red  female  199.0     500    yes
1    L  green    male   89.0     450     no
2    M   blue    male   99.0     300    yes
3    L  green  female  129.0     380     no
4    M    red  female   79.0     410    yes

###<a name = '4'></a> Backup

In [15]:
df = My_data.copy()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   size    5 non-null      object 
 1   color   5 non-null      object 
 2   gender  5 non-null      object 
 3   price   5 non-null      float64
 4   weight  5 non-null      int64  
 5   bought  5 non-null      object 
dtypes: float64(1), int64(1), object(4)
memory usage: 368.0+ bytes


###<a name = '5'></a>Change of data type

In [14]:
for col in [col]:
  df[col] = df[col].astype('category')

  df['weight'] = df['weight'].astype('float')
  
  

  df.info()


NameError: ignored

In [16]:
df.describe()

price      weight
count    5.000000    5.000000
mean   119.000000  408.000000
std     48.476799   75.299402
min     79.000000  300.000000
25%     89.000000  380.000000
50%     99.000000  410.000000
75%    129.000000  450.000000
max    199.000000  500.000000

In [17]:
df.describe().T

count   mean        std    min    25%    50%    75%    max
price     5.0  119.0  48.476799   79.0   89.0   99.0  129.0  199.0
weight    5.0  408.0  75.299402  300.0  380.0  410.0  450.0  500.0

In [18]:
df.describe(include=['category']).T

ValueError: ignored

### <a name = '6'> </a> LabelEncoder

In [19]:
from sklearn.preprocessing import LabelEncoder

la = LabelEncoder()
la.fit(df['bought'])
la.transform(df['bought'])

array([1, 0, 1, 0, 1])

In [20]:
la.fit_transform(df['bought'])

array([1, 0, 1, 0, 1])

In [21]:
df['bought'] = la.fit_transform(df['bought'])
df

size  color  gender  price  weight  bought
0   XL    red  female  199.0     500       1
1    L  green    male   89.0     450       0
2    M   blue    male   99.0     300       1
3    L  green  female  129.0     380       0
4    M    red  female   79.0     410       1

In [22]:
la.inverse_transform(df['bought'])

df['bought'] = la.inverse_transform(df['bought'])

df

size  color  gender  price  weight bought
0   XL    red  female  199.0     500    yes
1    L  green    male   89.0     450     no
2    M   blue    male   99.0     300    yes
3    L  green  female  129.0     380     no
4    M    red  female   79.0     410    yes

### <a name = '7'></a> OneHotEncoder

In [23]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse=False)
encoder.fit(df[['color']])

OneHotEncoder(categories='auto', drop=None, dtype=<class 'numpy.float64'>,
              handle_unknown='error', sparse=False)

In [24]:
encoder.transform(df[['color']])

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
encoder.categories_

[array(['blue', 'green', 'red'], dtype=object)]

In [26]:
encoder = OneHotEncoder(drop='first',sparse=False)
encoder.fit(df[['color']])
encoder.transform(df[['color']])

array([[0., 1.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [0., 1.]])

In [27]:
df

size  color  gender  price  weight bought
0   XL    red  female  199.0     500    yes
1    L  green    male   89.0     450     no
2    M   blue    male   99.0     300    yes
3    L  green  female  129.0     380     no
4    M    red  female   79.0     410    yes

### <a name='8'></a> Pandas get_dummies()

In [28]:
pd.get_dummies(data=df)

price  weight  size_L  ...  gender_male  bought_no  bought_yes
0  199.0     500       0  ...            0          0           1
1   89.0     450       1  ...            1          1           0
2   99.0     300       0  ...            1          0           1
3  129.0     380       1  ...            0          1           0
4   79.0     410       0  ...            0          0           1

[5 rows x 12 columns]

In [30]:
pd.get_dummies(data=df,drop_first=True)

price  weight  size_M  ...  color_red  gender_male  bought_yes
0  199.0     500       0  ...          1            0           1
1   89.0     450       0  ...          0            1           0
2   99.0     300       1  ...          0            1           1
3  129.0     380       0  ...          0            0           0
4   79.0     410       1  ...          1            0           1

[5 rows x 8 columns]

In [34]:
pd.get_dummies(data=df,drop_first=True,prefix_sep='|' )

price  weight  size|M  ...  color|red  gender|male  bought|yes
0  199.0     500       0  ...          1            0           1
1   89.0     450       0  ...          0            1           0
2   99.0     300       1  ...          0            1           1
3  129.0     380       0  ...          0            0           0
4   79.0     410       1  ...          1            0           1

[5 rows x 8 columns]

In [36]:
pd.get_dummies(data=df,drop_first=True,columns=['gender'])

size  color  price  weight bought  gender_male
0   XL    red  199.0     500    yes            0
1    L  green   89.0     450     no            1
2    M   blue   99.0     300    yes            1
3    L  green  129.0     380     no            0
4    M    red   79.0     410    yes            0